services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: https://todo.craig.wiki
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: vikunja
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: toyv8f5hn4c3ir4f7ewqjsow76hrah
    ports:
      - 3456:3456
    volumes:
      - ./files:/app/vikunja/files
      - ./config:/etc/vikunja
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: vikunja
      POSTGRES_USER: vikunja
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./psql-scripts:/opt/psql-scripts
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U $${POSTGRES_USER}
      interval: 2s
      timeout: 2s
      retries: 5
    restart: unless-stopped
    ports:
      - 5432:5432
  ntfy-handler:
    build:
      context: ./ntfy-handler  # Build from the Dockerfile in the current directory
    container_name: ntfy-handler
    ports:
      - "4567:8000"  # Expose FastAPI on port 8000
    volumes:
      - ./ntfy-handler/data:/app/data  # Persist SQLite database locally
    depends_on:
      - db  # Ensure the PostgreSQL service starts first
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=vikunja
      - DB_USER=vikunja
      - DB_PASSWORD=vikunja

networks: {}
